<a href="https://colab.research.google.com/github/billybongo07/LLM/blob/main/Attention_inclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
inputs = torch.nn.Embedding( 4, 8 )

In [3]:
inputs = inputs.weight.data
inputs

tensor([[ 1.0837,  0.9138, -1.0557,  1.4542, -2.1090, -1.8970, -0.1308,  0.0987],
        [ 0.7086,  0.0347,  1.8086, -0.3225,  0.0388,  1.6843, -1.7839,  1.6387],
        [ 0.2514,  0.0889, -0.8757,  0.9979,  2.0599,  0.5367,  0.7213, -0.1271],
        [ 0.4620,  1.6938,  0.8443,  0.0246,  0.3747,  2.1199,  1.9339, -1.6110]])

In [4]:
#set dimension
d_in = 8
d_out = 6

#create weight matrices
W_q = torch.nn.Parameter( torch.rand( d_in, d_out ), requires_grad=False )
W_k = torch.nn.Parameter( torch.rand( d_in, d_out ), requires_grad=False )
W_v = torch.nn.Parameter( torch.rand( d_in, d_out ), requires_grad=False )

In [7]:
#choose an input vector and transform it into the query vector using W_q
query = inputs[2] @ W_q
print("query:",query) #as you can see the vector is now of length six

query: tensor([2.5089, 0.7363, 0.8491, 1.2175, 2.5585, 1.6516])


In [6]:
#calc attention scores using the keys generated by W_k
keys = inputs @ W_k #in that order for both
values = inputs @ W_v
print("keys:", keys)
print("values:", values)

keys: tensor([[-2.0368, -2.2441, -0.0350, -0.7311, -0.1458, -0.5387],
        [ 3.0422,  1.8382,  2.3651,  0.4256,  0.1413,  2.0598],
        [ 1.0422,  1.5303,  1.3500,  2.7536,  2.4250,  1.6116],
        [ 2.2136,  3.3623,  3.5838,  3.8105,  1.6509,  3.8220]])
values: tensor([[-0.0468,  0.4867, -1.5348, -1.0969,  0.0755, -0.7580],
        [ 2.5398,  2.1142,  0.8665,  1.9760,  1.7090,  2.3759],
        [ 1.1153,  1.0315,  3.0773,  1.3969,  1.5101,  0.7640],
        [ 2.4899,  2.9923,  4.1360,  4.5847,  0.4613,  1.2621]])


In [8]:
attention_scores = query @ keys.T #in that order
attention_scores

tensor([-8.9447, 15.2758, 17.1062, 26.2475])

In [9]:
attention_weights = torch.softmax(attention_scores, dim=-1)
attention_weights


tensor([5.2018e-16, 1.7178e-05, 1.0714e-04, 9.9988e-01])

In [10]:
attention_weights.sum()

tensor(1.)

In [11]:
context_vector = attention_weights @ values #in that order
context_vector

tensor([2.4897, 2.9921, 4.1359, 4.5843, 0.4614, 1.2621])